import path from "node:path";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { getDb } from "@/lib/db";

// Applies the committed Drizzle migrations (`drizzle/` — generated by
// `npm run db:generate`, shipped into the container by the Dockerfile) to the
// `novedu_*` tables. Called from instrumentation.ts at every server start, so
// a deployed image always runs against the schema it was built for. Mastra's
// `mastra_*` tables are NOT touched — Mastra migrates its own schema.
//
// Bookkeeping lives in `novedu_drizzle_migrations` (prefix convention) — each
// migration runs exactly once per database, so concurrent/repeated starts are
// safe. Failures are NOT swallowed: a server that cannot reach the schema it
// expects must fail loudly at startup, not at the first student's request.
//
// `migrationsSchema` is pinned to `public` on purpose: the driver's default is a
// SEPARATE `drizzle` schema, and the bookkeeping belongs beside the tables it
// tracks. NOTE the migrator ALWAYS runs `CREATE SCHEMA IF NOT EXISTS <schema>`
// first — even for `public` — and Postgres checks CREATE on the DATABASE before
// the IF NOT EXISTS shortcut, so the app role needs that grant
// (scripts/db/provision.sql, docs/database.md "Privilege model") or the boot
// fails with "permission denied for database".
export async function runMigrations(): Promise<void> {
  await migrate(getDb(), {
    migrationsFolder: path.join(process.cwd(), "drizzle"),
    migrationsTable: "novedu_drizzle_migrations",
    migrationsSchema: "public",
  });
  console.log("db: novedu_* schema is up to date");
}
