import pageStyles from "@/app/page.module.css";
import { Notice } from "@/components/notice";
import { requireTeacherPage } from "@/components/require-teacher-page";
import { resolveAppOriginOr } from "@/lib/app-origin";
import { getActiveFile, isFileKind } from "@/lib/file-store";
import { filePublicUrl } from "@/lib/file-url";
import { StudentFileEditor } from "../../_studio/file-editor";

// ============================================================================
// APP-OWNED ROUTE SHELL — students do NOT edit this file.
// ============================================================================
// This is the boundary between the app and the student GUI module. It does the
// server-only work (teacher gate, DB read, public-URL resolution), then hands
// PLAIN STRING props to the student-owned `StudentFileEditor` in `_studio/`.
// Students build the GUI inside that component; everything below the props line
// is theirs. Mirrors `app/files/edit/[...name]/page.tsx` (the text editor route).
//
// The `[...name]` catch-all + the `_studio` folder name are intentional: see
// `docs/yaml-gui-student-contribution.md`.
export default async function GuiEditFilePage({ params }: { params: Promise<{ name: string[] }> }) {
  const denied = await requireTeacherPage();
  if (denied) return denied;

  const { name: segments } = await params;
  const name = segments.join("/");
  const file = await getActiveFile(name);

  if (file === undefined) {
    return (
      <main className={pageStyles.main}>
        <Notice heading="File temporarily unavailable">
          <p>This file could not be loaded right now. Try again in a moment.</p>
        </Notice>
      </main>
    );
  }
  if (file === null || !isFileKind(file.kind)) {
    return (
      <main className={pageStyles.main}>
        <Notice heading="File not found">
          <p>This file does not exist or has been deleted.</p>
        </Notice>
      </main>
    );
  }

  const publicUrl = filePublicUrl(await resolveAppOriginOr(""), file.name);

  return (
    <main className={pageStyles.main}>
      <StudentFileEditor
        name={file.name}
        kind={file.kind}
        initialContent={file.content}
        publicUrl={publicUrl}
      />
    </main>
  );
}
