/**
 * The llms.txt surface: a table of contents (`llms.txt`) pointing at a Markdown
 * twin of every chapter (`<section>/<chapter>.md`), plus the whole guide as one
 * document (`llms-full.txt`). Shape follows the llmstxt.org convention as
 * practised by large API docs (title, blockquote summary, `##` section lists of
 * `- [Title](absolute .md URL): description`).
 *
 * The corpus is plain Markdown with no MDX or components, so the twins are the
 * corpus bodies verbatim — no HTML round trip, nothing to sanitise. The routes
 * live in `src/pages/`; this module is the shared content builder.
 */
import { getCollection } from "astro:content";
import { GUIDE_DESCRIPTION, GUIDE_TITLE } from "./guide";
import { withBase } from "./paths";
import { SECTIONS, sectionDir, sectionLabel } from "./sections";

/** A corpus chapter, reduced to what the llms.txt surface needs. */
export interface Chapter {
  /** Content-relative id, which is also the URL path: "00-introduction/01-what-is-novedu". */
  id: string;
  title: string;
  description: string;
  /** Raw corpus Markdown, banner comment stripped. */
  body: string;
}

/** The generated-file banner every chapter opens with, plus any leading blank lines. */
const LEADING_COMMENT = /^\s*<!--[\s\S]*?-->\s*/;

/**
 * The chapter the llms.txt preamble points agents at for hands-on work: it
 * explains the `novedu-tutor-cli` skill and the CLI it drives. `buildIndex`
 * throws when the id no longer matches a chapter, so a corpus rename fails the
 * build instead of shipping a dead link.
 */
const CLI_CHAPTER_ID = "40-ai-llms/01-novedu-cli";

/**
 * Every chapter in reading order: sections in `SECTIONS` order, chapters by
 * their frontmatter `sidebar.order` within a section — the same key Starlight's
 * autogenerated sidebar sorts by, so the llms surface and the HTML guide can
 * never disagree about reading order. Filename is the tiebreak.
 */
export async function loadChapters(): Promise<Chapter[]> {
  const entries = await getCollection("docs", (entry) => !entry.data.draft);
  return entries
    .map((entry) => {
      const dir = sectionDir(entry.id);
      // Throws on a section missing from SECTIONS, so an unlisted corpus
      // directory fails the build instead of vanishing from the TOC — and
      // guarantees the findIndex below hits.
      sectionLabel(dir);
      return {
        rank: SECTIONS.findIndex((section) => section.dir === dir),
        order: entry.data.sidebar?.order ?? Number.MAX_SAFE_INTEGER,
        chapter: {
          id: entry.id,
          title: entry.data.title,
          description: entry.data.description ?? "",
          body: (entry.body ?? "").replace(LEADING_COMMENT, "").trim(),
        },
      };
    })
    .sort(
      (a, b) => a.rank - b.rank || a.order - b.order || a.chapter.id.localeCompare(b.chapter.id),
    )
    .map(({ chapter }) => chapter);
}

/** Absolute URL of a path under the deploy base, e.g. "llms.txt" or "<id>.md". */
export function docsUrl(site: URL | undefined, path: string): string {
  const relative = withBase(import.meta.env.BASE_URL, path);
  return site ? new URL(relative, site).href : relative;
}

/** Chapter rendered as Markdown: title, description blockquote, body. */
function chapterSection(chapter: Chapter): string {
  const heading = `# ${chapter.title}`;
  const description = chapter.description ? `\n\n> ${chapter.description}` : "";
  return `${heading}${description}\n\n${chapter.body}\n`;
}

/**
 * A chapter's Markdown twin: the chapter itself plus a one-line pointer back to
 * the index and the human page, so an agent that lands here can navigate on.
 */
export function chapterTwin(chapter: Chapter, site: URL | undefined): string {
  const index = docsUrl(site, "llms.txt");
  const page = docsUrl(site, `${chapter.id}/`);
  return `${chapterSection(chapter)}
---

_From the [${GUIDE_TITLE}](${page}). Full index of Markdown pages: ${index}_
`;
}

/** `llms.txt`: the table of contents. */
export async function buildIndex(site: URL | undefined): Promise<string> {
  const chapters = await loadChapters();
  const cliChapter = chapters.find((chapter) => chapter.id === CLI_CHAPTER_ID);
  if (!cliChapter) {
    throw new Error(
      `llms.txt points agents at chapter "${CLI_CHAPTER_ID}", which no longer exists — update CLI_CHAPTER_ID in src/lib/llms.ts`,
    );
  }
  const lines = [
    `# ${GUIDE_TITLE}`,
    "",
    `> ${GUIDE_DESCRIPTION}`,
    "",
    `Every chapter below is linked as a Markdown file. Appending \`.md\` to any page URL of the HTML guide returns the same Markdown.`,
    "",
    `Agents that want to work with Novedu hands-on (validate activity YAML, inspect the exact prompts an activity produces, create and manage codes) can install the \`novedu-tutor-cli\` skill, which teaches an agent to drive the \`@novedu/cli\`: see [${cliChapter.title}](${docsUrl(site, `${CLI_CHAPTER_ID}.md`)}).`,
    "",
    "## Documentation sets",
    `- [Complete guide](${docsUrl(site, "llms-full.txt")}): every chapter of the teacher guide concatenated into one Markdown document.`,
  ];
  for (const section of SECTIONS) {
    const inSection = chapters.filter((chapter) => sectionDir(chapter.id) === section.dir);
    if (inSection.length === 0) continue;
    lines.push("", `## ${section.label}`);
    for (const chapter of inSection) {
      const url = docsUrl(site, `${chapter.id}.md`);
      lines.push(
        `- [${chapter.title}](${url})${chapter.description ? `: ${chapter.description}` : ""}`,
      );
    }
  }
  return `${lines.join("\n")}\n`;
}

/** `llms-full.txt`: the whole guide as one Markdown document. */
export async function buildFullText(): Promise<string> {
  const chapters = await loadChapters();
  const header = `<SYSTEM>This is the complete ${GUIDE_TITLE}, every chapter concatenated in reading order.</SYSTEM>`;
  return `${header}\n\n${chapters.map(chapterSection).join("\n")}`;
}
