import { defineCollection } from "astro:content";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";
import { z } from "astro/zod";

export const collections = {
  docs: defineCollection({
    // Starlight's docsLoader reads src/content/docs, where the corpus lives as
    // real files — so it is read in place, with no copy step. A plain glob loader
    // with an out-of-root base breaks Starlight's autogenerated sidebar: it
    // resolves entries via filePath relative to src/content/docs.
    // If the corpus becomes unreadable, the collection comes up empty — the
    // post-build scripts/verify-dist.mjs fails the build loudly.
    loader: docsLoader(),
    schema: docsSchema({
      extend: z.object({
        audience: z.string(),
        keywords: z.array(z.string()),
        // Optional per the corpus frontmatter contract ("omit if there are none").
        related: z.array(z.string()).default([]),
      }),
    }),
  }),
};
