import pageStyles from "@/app/page.module.css";
import { requireTeacherPage } from "@/components/require-teacher-page";
import { type FileKind, loadYamlFromUrlAction } from "@/lib/yaml-files";
import { StudentFileViewer } from "../_studio/file-viewer";

// ============================================================================
// APP-OWNED ROUTE SHELL — students do NOT edit this file.
// ============================================================================
// Read-only "View in GUI" entry point, reached from /validate-tutor with
// `?url=<public YAML url>&kind=tutor|fragment`. It gates (teacher-only, like the
// validate page), loads the YAML server-side through the same
// `loadYamlFromUrlAction` students use (so app-hosted / relative / external URLs
// all resolve identically and the SSRF guard lives in one place), then hands
// PLAIN props to the student-owned `StudentFileViewer` in `_studio/`.
export default async function GuiViewFilePage({
  searchParams,
}: {
  searchParams: Promise<{ url?: string | string[]; kind?: string | string[] }>;
}) {
  const denied = await requireTeacherPage();
  if (denied) return denied;

  const sp = await searchParams;
  const url = typeof sp.url === "string" ? sp.url : "";
  const kind: FileKind = sp.kind === "fragment" ? "fragment" : "tutor";

  let initialContent: string | null = null;
  let loadError: string | undefined;
  if (!url) {
    loadError = "No URL was provided.";
  } else {
    const loaded = await loadYamlFromUrlAction({ url });
    if (loaded.ok) initialContent = loaded.content;
    else loadError = loaded.message;
  }

  return (
    <main className={pageStyles.main}>
      <StudentFileViewer
        url={url}
        kind={kind}
        initialContent={initialContent}
        loadError={loadError}
      />
    </main>
  );
}
